export const prompts = {
  1: "Example prompt",
  2: "Guys Drink",
  3: "Girls Drink",
  4: "Roll the dice one more time",
  5: "Add a shot of hard liquor to your drink",
  6: "Play category",
  7: "Drink as much as the number of vowels in your full name",
  8: "Waterfall - You may stop drinking once the person to your left stops",
  9: "Give out 3 sips to a person that is at least 5 tiles below you",
  10: "Do 10 push ups or drink",
  12: "Punishment - drink 1 shot",
  13: "Create a rule! The rule will apply for the rest of the game.",
  14: "Rock paper scissors with the person closest to your tile",
  15: "Choose someone ahead of you to be your buddy, if you are first drink 2 sips",
  16: "Waterfall - You may stop drinking once the person to your left stops",
  17: "Punishment - Take 1 shot",
  18: "Ngupil on camera or drink for 5 seconds",
  19: "Player in even-numbered boxes, drink 2 sips",
  20: "Give out 5 sips",
  21: "Sit without support and your backs against a wall for the next 3 turns, if you fail drink 4 sips",
  22: "Pick someone and guess the color of their underwear. If you guess correctly, he/she drinks, otherwise you drink",
  23: "Give out 5 sips",
  24: "Waterfall - You may stop drinking once the person to your left stops",
  25: "Show your bed to the crowd, if you have not make your bed, drink 3 sips",
  26: "Lick the floor on camera or drink 5 sips",
  27: "Player in odd-numbered boxes, drink 2 sips",
  28: "Truth or dare",
  30: "Eat a spoonful of salt or chug your drink",
  31: "Voting - Whoever is most likely to get kicked out of the club first, drink 2 sips",
  32: "Choose someone ahead of you to be your buddy, if you are first drink 2 sips",
  33: "Drink 2 sips of anything in the fridge yang disuruh audience",
  34: "Show everyone the last photo on your phone. If not, drink 2 sips.",
  35: "Plank challenge (2 mins tops? lol)",
  36: "Imitate another player. First person to guess correctly picks someone to drink",
  37: "Punishment - Take 1 shot",
  38: "Make up a math question, first one to answer give 3 sips",
  39: "Create a rule! The rule will apply for the rest of the game.",
  40: "Waterfall - You may stop drinking once the person to your left stops",
  41: "Give out 5 sips",
  42: "Play 24 (4nums.com)",
  43: "Tongue twister - satu biru, dua biru, tiga biru, empat biru, lima biru",
  44: "Punishment - Take 1 shot",
  45: "Who pooped most recently, drink 2 sips",
  46: "Give out 5 sips",
  48: "Waterfall - You may stop drinking once the person to your left stops",
  49: "Choose a number in the board, everyone that is currently in that number drink 2 sips",
  50: "Cut 2 cm of at least 5 strands of your hair or down your drink",
  52: "Punishment - Take 1 shot",
  53: "Balance an item of your choice on your head for the next 2 turns",
  54: "Tell a lie and a truth, make a unanimous  decision which one is the lie. If they are wrong, all drink 2 sips. if they are right, you drink 3 sips.",
  55: "Twerk for 5 seconds, or drink 3 sips",
  56: "Waterfall - You may stop drinking once the person to your left stops",
  57: "Put your finger on your nose, the last one to do it drinks.",
  58: "Punishment - Take 1 shot",
  59: "Play never have i ever",
  60: "Choose someone ahead of you to be your buddy, if you are first drink 2 sips",
  61: "Give out 5 sips",
  62: "Down you drink!",
  63: "Punishment - Take 1 shot",
  64: "1st winner - give out 10 sips. 2nd winner - give out 8 sips. 3rd winner - give out 6 sips"
}