export const prompts = {
  1: "Guys Drink",
  2: "Girls Drink",
  3: "Roll the dice one more time",
  4: "Add a shot of hard liquor to drink",
  5: "Category",
  6: "Drink as many vowels in your full name",
  7: "Waterfall - Stop drinking once the person to your left stops",
  8: "Give out 3 sips to a person that is at least 5 steps below you",
  9: "10 push ups or drink",
  10: "Power up - your next move, dice roll x2",
  11: "punishment - drink 1 shot",
  12: "Create a rule! The rule will apply for the rest of the game.",
  13: "Create a rule! The rule will apply for the rest of the game.",
  14: "suit",
  15: "Choose someone above you to be your buddy, if you are first drink 2 sips",
  16: "Waterfall - stop drinking when the person on your right stops drinking",
  17: "punishment - drink 1 shot",
  18: "ngupil on camera or drink for 5 seconds",
  19: "Player in even number box, drink 2 sips",
  20: "reward for naik ladder - give out 5 sips",
  21: "sit on a wall for the next 3 turns, if you fail drink 4 sips",
  22: "Pick someone and guess the color of their underwear. if you guess correctly, they drink, otherwise you drink",
  23: "reward for naik ladder - give out 5 sips",
  24: "Waterfall - stop drinking when the person on your right stops drinking",
  25: "show your bed to the crowd, if you have not make your bed, drink 3 sips",
  26: "Lick the floor on camera or drink 5 sips",
  27: "Player in odd-numbered box, drink 2 sips",
  28: "truth or dare",
  29: "Power Down :( Your next move, dice roll -2",
  30: "Eat a spoonful of salt or chug your drink",
  31: "vote for most likely to get kicked out of the club first, drink 2 sips",
  32: "Choose someone above you to be your buddy, if you are first drink 2 sips",
  33: "drink 2 sips of anything in the fridge yang disuruh audience",
  34: "Show everyone the last photo on your phone. If not, drink 2 sips.",
  35: "plank challenge (2 mins tops? lol)",
  36: "Imitate another player. First person to guess correctly picks someone to drink",
  37: "punishment - drink 1 shot",
  38: "Make up a math question, first one to answer give 3 sips",
  39: "Create a rule! The rule will apply for the rest of the game.",
  40: "Waterfall - stop drinking when the person on your right stops drinking",
  41: "reward for naik ladder - give out 5 sips",
  42: "play 24",
  43: "tongue twister - satu biru, dua biru, tiga biru, empat biru, lima biru",
  44: "punishment - drink 1 shot",
  45: "Who pooped most recently, drink 2 sips",
  46: "reward for naik ladder - give out 5 sips",
  47: "Move a player -5 boxes or give out drinks",
  48: "Waterfall - stop drinking when the person on your right stops drinking",
  49: "Choose a number in the board, everyone that is currently in that number drink 2 sips",
  50: "Cut 2 cm of at least 5 strands of your hair or down your drink",
  51: "It's your unlucky day, move -2 boxes",
  52: "punishment - drink 1 shot",
  53: "Balance an item of your choice on your head for the next 2 turns",
  54: "Tell a lie and a truth, make a unanimous  decision which one is the lie. If they are wrong, all drink 2 sips. if they are right, you drink 3 sips.",
  55: "Twerk for 5 seconds, or drink 3 sips",
  56: "Waterfall - stop drinking when the person on your right stops drinking",
  57: "Put your finger on your nose, the last one to do it drinks.",
  58: "punishment - drink 1 shot",
  59: "never have i ever",
  60: "Choose someone above you to be your buddy, if you are first drink 2 sips",
  61: "reward for naik ladder - give out 5 sips",
  62: "Down you drink! - box 62",
  63: "punishment - drink 1 shot",
  64: "1st winner - give out 10 sips. 2nd winner - give out 8 sips. 3rd winner - give out 6 sips"
}